out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: True
  project: peptides-struct_lg_backtrack
dataset:
  format: OGB
  name: peptides-structural_lg_backtrack
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: AtomLG+LapPE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: BondLG
  edge_encoder_bn: False
posenc_LapPE:
  enable: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none
train:
  mode: custom
  batch_size: 200
  eval_period: 1
  ckpt_period: 100
model:
  type: custom_gnn
  loss_fun: l1
  graph_pooling: mean
gnn:
  batchnorm: True
  head: mlp_graph
  layers_pre_mp: 0
  layers_mp: 6
  layers_post_mp: 3
  dim_inner: 228
  layer_type: gcnconv
  act: gelu
  residual: True
  dropout: 0.1
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 300
  scheduler: cosine_with_warmup
  num_warmup_epochs: 50