out_dir: results
metric_best: f1
wandb:
  use: True
  project: Pascal
dataset:
  format: PyG-VOCSuperpixels_lg_bt
  name: edge_wt_only_coord
  slic_compactness: 30
  task: graph  # Even if VOC is node-level task, this needs to be set as 'graph'
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: VOCNodeLG+LapPE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: VOCEdgeLG
  edge_encoder_bn: False
posenc_LapPE:
  enable: False
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none
posenc_RWSE:
  enable: False
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 28
  raw_norm_type: BatchNorm
train:
  mode: custom
  # batch_size: 50
  batch_size: 30
  eval_period: 1
  ckpt_period: 100
  # eval_smoothing_metrics: True
model:
  type: custom_gnn
  loss_fun: weighted_cross_entropy
gnn:
  head: inductive_node
  layers_pre_mp: 0
  layers_mp: 10
  layers_post_mp: 2
  dim_inner: 144
  layer_type: gineconv
  act: gelu
  residual: True
  dropout: 0.2
  linegraph: True
  lgvariant: 20
optim:
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 50
