out_dir: results
metric_best: mrr
num_workers: 16
wandb:
  use: True
  project: pcqm4m-contact_lg
dataset:
  format: OGB
  name: PCQM4Mv2Contact_lg-shuffle
  task: graph  # PCQM4Mv2Contact is edge-level task, but because it is inductive, set to 'graph'
  task_type: classification
  resample_negative: True
  # resample_negative: False
  transductive: False
  node_encoder: True
  node_encoder_name: AtomLG
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: BondLG
  edge_encoder_bn: False
train:
  mode: custom
  batch_size: 500
  eval_period: 1
  ckpt_period: 100
  # eval_smoothing_metrics: True
model:
  type: custom_gnn
  loss_fun: cross_entropy
  edge_decoding: dot
gnn:
  head: inductive_edge
  layers_pre_mp: 0
  layers_mp: 8
  layers_post_mp: 1
  dim_inner: 204
  layer_type: gcnconv
  act: gelu
  residual: True
  dropout: 0.1
  batchnorm: False
  linegraph: True
  lgvariant: 30
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 150
  scheduler: cosine_with_warmup
  num_warmup_epochs: 50
