out_dir: results
metric_best: f1
wandb:
  use: True
  project: Pascal
dataset:
  format: PyG-VOCSuperpixels_lg_bt
  name: edge_wt_only_coord  # Alternative: edge_wt_region_boundary
  slic_compactness: 30
  task: graph  # Even if VOC is node-level task, this needs to be set as 'graph'
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: VOCNodeLG+LapPE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: VOCEdgeLG
  edge_encoder_bn: False
posenc_LapPE:
  dim_pe: 16
  eigen:
    eigvec_norm: L2
    laplacian_norm: sym
    max_freqs: 10
  enable: true
  layers: 2
  model: DeepSet
  n_heads: 4
  raw_norm_type: none
train:
  mode: custom
  batch_size: 28
  eval_period: 1
  ckpt_period: 100
model:
  type: custom_gnn
  loss_fun: weighted_cross_entropy
gnn:
  head: inductive_node
  layers_pre_mp: 0
  layers_mp: 8
  layers_post_mp: 3
  dim_inner: 220
  layer_type: gcnconv
  stage_type: stack
  batchnorm: True
  act: gelu
  residual: True
  dropout: 0.0
  agg: mean
  normalize_adj: False
  linegraph: True
  lgvariant: 20
optim:
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0005
  max_epoch: 500
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 10
  min_lr: 1e-5
  lr_decay: 0.1
  momentum: 0.9
  steps:
  - 30
  - 60
  - 90