out_dir: results
metric_best: ap
wandb:
  use: True
  project: peptides-func
dataset:
  dir: datasets
  format: OGB
  name: peptides-functional
  task: graph
  task_type: classification_multilabel
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+LapPE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_LapPE:
  dim_pe: 16
  eigen:
    eigvec_norm: L2
    laplacian_norm: sym
    max_freqs: 10
  enable: true
  layers: 2
  model: DeepSet
  n_heads: 4
  raw_norm_type: none
train:
  mode: custom
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
model:
  type: custom_gnn
  loss_fun: cross_entropy
  graph_pooling: mean
gnn:
  layers_pre_mp: 0
  layers_mp: 15
  layers_post_mp: 1
  dim_inner: 208
  layer_type: gineconv
  stage_type: stack
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
  residual: False
  linegraph: False
optim:
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.01
  max_epoch: 500
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 20
  min_lr: 1e-5
  lr_decay: 0.1
  momentum: 0.9
  steps:
  - 30
  - 60
  - 90
